apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-backend-facade-deployment
  labels:
    app: web-backend-facade
    owner: Ferum-bot
    tier: backend
    stage: production
    infrastructure: js
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-backend-facade-application
      stage: production
  template:
    metadata:
      labels:
        app: web-backend-facade-application
        stage: production
    spec:
      containers:
        - name: web-backend-facade-container
          image: cr.yandex/$REGISTRY_ID/$REPOSITORY_NAME:$IMAGE_TAG
          livenessProbe:
            httpGet:
              port: 8585
              path: /metrics
            initialDelaySeconds: 40
            periodSeconds: 20
            readinessProbe:
              httpGet:
                port: 8585
                path: /metrics
              initialDelaySeconds: 40
              periodSeconds: 20
            startupProbe:
              httpGet:
                port: 8585
                path: /metrics
              failureThreshold: 30
              periodSeconds: 10
          ports:
            - containerPort: 8585
              hostPort: 8585
          env:
            - name: MONO_BACKEND_URL
              value: {{MONO_BACKEND_URL}}